version: '3.7'
services:
  authservicedb:
    image: postgres:13
    container_name: authservicedb
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose: 
      - 5432
    ports: 
      - "5432:5432"
    networks:
      - authservice_net 
  authserviceapi:
    container_name: authserviceapi
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - authservicedb
    networks:
      - authservice_net
    ports:
      - "8000:8000"
networks:
  authservice_net:
    driver: bridge